package com.hakob.financialhke.db.dbconfig

import app.cash.sqldelight.db.SqlDriver
import com.hakob.financialhke.database.Database

expect class DriverFactory {
    fun createDriver(): SqlDriver
}

// might need to create DB manually and use it somehow. but in general will use *Queries classes
// generated by sqldelight
fun createDatabase(driverFactory: DriverFactory): Database {
    val driver: SqlDriver = driverFactory.createDriver()
    val database = Database(driver)

    // Do more work with the database (see below).
    return database
}